// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(lipabusinesslibFFI)
import lipabusinesslibFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_lipabusinesslib_882b_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_lipabusinesslib_882b_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a libray of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// A helper class to read values out of a byte buffer.
fileprivate class Reader {
    let data: Data
    var offset: Data.Index

    init(data: Data) {
        self.data = data
        self.offset = 0
    }

    // Reads an integer at the current offset, in big-endian order, and advances
    // the offset on success. Throws if reading the integer would move the
    // offset past the end of the buffer.
    func readInt<T: FixedWidthInteger>() throws -> T {
        let range = offset..<offset + MemoryLayout<T>.size
        guard data.count >= range.upperBound else {
            throw UniffiInternalError.bufferOverflow
        }
        if T.self == UInt8.self {
            let value = data[offset]
            offset += 1
            return value as! T
        }
        var value: T = 0
        let _ = withUnsafeMutableBytes(of: &value, { data.copyBytes(to: $0, from: range)})
        offset = range.upperBound
        return value.bigEndian
    }

    // Reads an arbitrary number of bytes, to be used to read
    // raw bytes, this is useful when lifting strings
    func readBytes(count: Int) throws -> Array<UInt8> {
        let range = offset..<(offset+count)
        guard data.count >= range.upperBound else {
            throw UniffiInternalError.bufferOverflow
        }
        var value = [UInt8](repeating: 0, count: count)
        value.withUnsafeMutableBufferPointer({ buffer in
            data.copyBytes(to: buffer, from: range)
        })
        offset = range.upperBound
        return value
    }

    // Reads a float at the current offset.
    @inlinable
    func readFloat() throws -> Float {
        return Float(bitPattern: try readInt())
    }

    // Reads a float at the current offset.
    @inlinable
    func readDouble() throws -> Double {
        return Double(bitPattern: try readInt())
    }

    // Indicates if the offset has reached the end of the buffer.
    @inlinable
    func hasRemaining() -> Bool {
        return offset < data.count
    }
}

// A helper class to write values into a byte buffer.
fileprivate class Writer {
    var bytes: [UInt8]
    var offset: Array<UInt8>.Index

    init() {
        self.bytes = []
        self.offset = 0
    }

    func writeBytes<S>(_ byteArr: S) where S: Sequence, S.Element == UInt8 {
        bytes.append(contentsOf: byteArr)
    }

    // Writes an integer in big-endian order.
    //
    // Warning: make sure what you are trying to write
    // is in the correct type!
    func writeInt<T: FixedWidthInteger>(_ value: T) {
        var value = value.bigEndian
        withUnsafeBytes(of: &value) { bytes.append(contentsOf: $0) }
    }

    @inlinable
    func writeFloat(_ value: Float) {
        writeInt(value.bitPattern)
    }

    @inlinable
    func writeDouble(_ value: Double) {
        writeInt(value.bitPattern)
    }
}

// Protocol for types that transfer other types across the FFI. This is
// analogous go the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: Reader) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: Writer)
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
    static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    static func lift(_ buf: RustBuffer) throws -> SwiftType {
        let reader = Reader(data: Data(rustBuffer: buf))
        let value = try read(from: reader)
        if reader.hasRemaining() {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    static func lower(_ value: SwiftType) -> RustBuffer {
          let writer = Writer()
          write(value, into: writer)
          return RustBuffer(bytes: writer.bytes)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_PANIC: Int8 = 2

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: {
        $0.deallocate()
        return UniffiInternalError.unexpectedRustCallError
    })
}

private func rustCallWithError<T, F: FfiConverter>
    (_ errorFfiConverter: F.Type, _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T
    where F.SwiftType: Error, F.FfiType == RustBuffer
    {
    try makeRustCall(callback, errorHandler: { return try errorFfiConverter.lift($0) })
}

private func makeRustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T, errorHandler: (RustBuffer) throws -> Error) throws -> T {
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    switch callStatus.code {
        case CALL_SUCCESS:
            return returnedVal

        case CALL_ERROR:
            throw try errorHandler(callStatus.errorBuf)

        case CALL_PANIC:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

// Public interface members begin here.


fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    static func read(from buf: Reader) throws -> UInt64 {
        return try lift(buf.readInt())
    }

    static func write(_ value: SwiftType, into buf: Writer) {
        buf.writeInt(lower(value))
    }
}

fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    static func read(from buf: Reader) throws -> String {
        let len: Int32 = try buf.readInt()
        return String(bytes: try buf.readBytes(count: Int(len)), encoding: String.Encoding.utf8)!
    }

    static func write(_ value: String, into buf: Writer) {
        let len = Int32(value.utf8.count)
        buf.writeInt(len)
        buf.writeBytes(value.utf8)
    }
}


public protocol WalletProtocol {
    func `syncBalance`() throws -> Balance
    
}

public class Wallet: WalletProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }
    public convenience init(`config`: Config) throws {
        self.init(unsafeFromRawPointer: try
    
    rustCallWithError(FfiConverterTypeWalletError.self) {
    
    lipabusinesslib_882b_Wallet_new(
        FfiConverterTypeConfig.lower(`config`), $0)
})
    }

    deinit {
        try! rustCall { ffi_lipabusinesslib_882b_Wallet_object_free(pointer, $0) }
    }

    

    
    public func `syncBalance`() throws -> Balance {
        return try FfiConverterTypeBalance.lift(
            try
    rustCallWithError(FfiConverterTypeWalletError.self) {
    lipabusinesslib_882b_Wallet_sync_balance(self.pointer, $0
    )
}
        )
    }
    
}


fileprivate struct FfiConverterTypeWallet: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Wallet

    static func read(from buf: Reader) throws -> Wallet {
        let v: UInt64 = try buf.readInt()
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    static func write(_ value: Wallet, into buf: Writer) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        buf.writeInt(UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Wallet {
        return Wallet(unsafeFromRawPointer: pointer)
    }

    static func lower(_ value: Wallet) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}


public struct Balance {
    public var `confirmed`: UInt64
    public var `trustedPending`: UInt64
    public var `untrustedPending`: UInt64
    public var `immature`: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(`confirmed`: UInt64, `trustedPending`: UInt64, `untrustedPending`: UInt64, `immature`: UInt64) {
        self.`confirmed` = `confirmed`
        self.`trustedPending` = `trustedPending`
        self.`untrustedPending` = `untrustedPending`
        self.`immature` = `immature`
    }
}


extension Balance: Equatable, Hashable {
    public static func ==(lhs: Balance, rhs: Balance) -> Bool {
        if lhs.`confirmed` != rhs.`confirmed` {
            return false
        }
        if lhs.`trustedPending` != rhs.`trustedPending` {
            return false
        }
        if lhs.`untrustedPending` != rhs.`untrustedPending` {
            return false
        }
        if lhs.`immature` != rhs.`immature` {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(`confirmed`)
        hasher.combine(`trustedPending`)
        hasher.combine(`untrustedPending`)
        hasher.combine(`immature`)
    }
}


fileprivate struct FfiConverterTypeBalance: FfiConverterRustBuffer {
    fileprivate static func read(from buf: Reader) throws -> Balance {
        return try Balance(
            `confirmed`: FfiConverterUInt64.read(from: buf), 
            `trustedPending`: FfiConverterUInt64.read(from: buf), 
            `untrustedPending`: FfiConverterUInt64.read(from: buf), 
            `immature`: FfiConverterUInt64.read(from: buf)
        )
    }

    fileprivate static func write(_ value: Balance, into buf: Writer) {
        FfiConverterUInt64.write(value.`confirmed`, into: buf)
        FfiConverterUInt64.write(value.`trustedPending`, into: buf)
        FfiConverterUInt64.write(value.`untrustedPending`, into: buf)
        FfiConverterUInt64.write(value.`immature`, into: buf)
    }
}


public struct Config {
    public var `electrumUrl`: String
    public var `walletDbPath`: String
    public var `network`: Network
    public var `watchDescriptor`: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(`electrumUrl`: String, `walletDbPath`: String, `network`: Network, `watchDescriptor`: String) {
        self.`electrumUrl` = `electrumUrl`
        self.`walletDbPath` = `walletDbPath`
        self.`network` = `network`
        self.`watchDescriptor` = `watchDescriptor`
    }
}


extension Config: Equatable, Hashable {
    public static func ==(lhs: Config, rhs: Config) -> Bool {
        if lhs.`electrumUrl` != rhs.`electrumUrl` {
            return false
        }
        if lhs.`walletDbPath` != rhs.`walletDbPath` {
            return false
        }
        if lhs.`network` != rhs.`network` {
            return false
        }
        if lhs.`watchDescriptor` != rhs.`watchDescriptor` {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(`electrumUrl`)
        hasher.combine(`walletDbPath`)
        hasher.combine(`network`)
        hasher.combine(`watchDescriptor`)
    }
}


fileprivate struct FfiConverterTypeConfig: FfiConverterRustBuffer {
    fileprivate static func read(from buf: Reader) throws -> Config {
        return try Config(
            `electrumUrl`: FfiConverterString.read(from: buf), 
            `walletDbPath`: FfiConverterString.read(from: buf), 
            `network`: FfiConverterTypeNetwork.read(from: buf), 
            `watchDescriptor`: FfiConverterString.read(from: buf)
        )
    }

    fileprivate static func write(_ value: Config, into buf: Writer) {
        FfiConverterString.write(value.`electrumUrl`, into: buf)
        FfiConverterString.write(value.`walletDbPath`, into: buf)
        FfiConverterTypeNetwork.write(value.`network`, into: buf)
        FfiConverterString.write(value.`watchDescriptor`, into: buf)
    }
}


public struct Descriptors {
    public var `spendDescriptor`: String
    public var `watchDescriptor`: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(`spendDescriptor`: String, `watchDescriptor`: String) {
        self.`spendDescriptor` = `spendDescriptor`
        self.`watchDescriptor` = `watchDescriptor`
    }
}


extension Descriptors: Equatable, Hashable {
    public static func ==(lhs: Descriptors, rhs: Descriptors) -> Bool {
        if lhs.`spendDescriptor` != rhs.`spendDescriptor` {
            return false
        }
        if lhs.`watchDescriptor` != rhs.`watchDescriptor` {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(`spendDescriptor`)
        hasher.combine(`watchDescriptor`)
    }
}


fileprivate struct FfiConverterTypeDescriptors: FfiConverterRustBuffer {
    fileprivate static func read(from buf: Reader) throws -> Descriptors {
        return try Descriptors(
            `spendDescriptor`: FfiConverterString.read(from: buf), 
            `watchDescriptor`: FfiConverterString.read(from: buf)
        )
    }

    fileprivate static func write(_ value: Descriptors, into buf: Writer) {
        FfiConverterString.write(value.`spendDescriptor`, into: buf)
        FfiConverterString.write(value.`watchDescriptor`, into: buf)
    }
}


public struct KeyPair {
    public var `secretKey`: String
    public var `publicKey`: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(`secretKey`: String, `publicKey`: String) {
        self.`secretKey` = `secretKey`
        self.`publicKey` = `publicKey`
    }
}


extension KeyPair: Equatable, Hashable {
    public static func ==(lhs: KeyPair, rhs: KeyPair) -> Bool {
        if lhs.`secretKey` != rhs.`secretKey` {
            return false
        }
        if lhs.`publicKey` != rhs.`publicKey` {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(`secretKey`)
        hasher.combine(`publicKey`)
    }
}


fileprivate struct FfiConverterTypeKeyPair: FfiConverterRustBuffer {
    fileprivate static func read(from buf: Reader) throws -> KeyPair {
        return try KeyPair(
            `secretKey`: FfiConverterString.read(from: buf), 
            `publicKey`: FfiConverterString.read(from: buf)
        )
    }

    fileprivate static func write(_ value: KeyPair, into buf: Writer) {
        FfiConverterString.write(value.`secretKey`, into: buf)
        FfiConverterString.write(value.`publicKey`, into: buf)
    }
}


public struct LipaKeys {
    public var `authKeypair`: KeyPair
    public var `walletDescriptors`: Descriptors

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(`authKeypair`: KeyPair, `walletDescriptors`: Descriptors) {
        self.`authKeypair` = `authKeypair`
        self.`walletDescriptors` = `walletDescriptors`
    }
}


extension LipaKeys: Equatable, Hashable {
    public static func ==(lhs: LipaKeys, rhs: LipaKeys) -> Bool {
        if lhs.`authKeypair` != rhs.`authKeypair` {
            return false
        }
        if lhs.`walletDescriptors` != rhs.`walletDescriptors` {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(`authKeypair`)
        hasher.combine(`walletDescriptors`)
    }
}


fileprivate struct FfiConverterTypeLipaKeys: FfiConverterRustBuffer {
    fileprivate static func read(from buf: Reader) throws -> LipaKeys {
        return try LipaKeys(
            `authKeypair`: FfiConverterTypeKeyPair.read(from: buf), 
            `walletDescriptors`: FfiConverterTypeDescriptors.read(from: buf)
        )
    }

    fileprivate static func write(_ value: LipaKeys, into buf: Writer) {
        FfiConverterTypeKeyPair.write(value.`authKeypair`, into: buf)
        FfiConverterTypeDescriptors.write(value.`walletDescriptors`, into: buf)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
public enum LogLevel {
    
    case `error`
    case `warn`
    case `info`
    case `debug`
    case `trace`
}

fileprivate struct FfiConverterTypeLogLevel: FfiConverterRustBuffer {
    typealias SwiftType = LogLevel

    static func read(from buf: Reader) throws -> LogLevel {
        let variant: Int32 = try buf.readInt()
        switch variant {
        
        case 1: return .`error`
        
        case 2: return .`warn`
        
        case 3: return .`info`
        
        case 4: return .`debug`
        
        case 5: return .`trace`
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    static func write(_ value: LogLevel, into buf: Writer) {
        switch value {
        
        
        case .`error`:
            buf.writeInt(Int32(1))
        
        
        case .`warn`:
            buf.writeInt(Int32(2))
        
        
        case .`info`:
            buf.writeInt(Int32(3))
        
        
        case .`debug`:
            buf.writeInt(Int32(4))
        
        
        case .`trace`:
            buf.writeInt(Int32(5))
        
        }
    }
}


extension LogLevel: Equatable, Hashable {}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
public enum Network {
    
    case `bitcoin`
    case `testnet`
    case `signet`
    case `regtest`
}

fileprivate struct FfiConverterTypeNetwork: FfiConverterRustBuffer {
    typealias SwiftType = Network

    static func read(from buf: Reader) throws -> Network {
        let variant: Int32 = try buf.readInt()
        switch variant {
        
        case 1: return .`bitcoin`
        
        case 2: return .`testnet`
        
        case 3: return .`signet`
        
        case 4: return .`regtest`
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    static func write(_ value: Network, into buf: Writer) {
        switch value {
        
        
        case .`bitcoin`:
            buf.writeInt(Int32(1))
        
        
        case .`testnet`:
            buf.writeInt(Int32(2))
        
        
        case .`signet`:
            buf.writeInt(Int32(3))
        
        
        case .`regtest`:
            buf.writeInt(Int32(4))
        
        }
    }
}


extension Network: Equatable, Hashable {}



public enum KeyDerivationError {

    
    
    // Simple error enums only carry a message
    case Derivation(message: String)
    
    // Simple error enums only carry a message
    case DerivationPathParse(message: String)
    
    // Simple error enums only carry a message
    case DescKeyFromXPriv(message: String)
    
    // Simple error enums only carry a message
    case DescPubKeyFromDescSecretKey(message: String)
    
    // Simple error enums only carry a message
    case DescSecretKeyFromDescKey(message: String)
    
    // Simple error enums only carry a message
    case ExtendedKeyFromMnemonic(message: String)
    
    // Simple error enums only carry a message
    case ExtendedKeyFromXPriv(message: String)
    
    // Simple error enums only carry a message
    case MnemonicParsing(message: String)
    
    // Simple error enums only carry a message
    case XPrivFromExtendedKey(message: String)
    
}

fileprivate struct FfiConverterTypeKeyDerivationError: FfiConverterRustBuffer {
    typealias SwiftType = KeyDerivationError

    static func read(from buf: Reader) throws -> KeyDerivationError {
        let variant: Int32 = try buf.readInt()
        switch variant {

        

        
        case 1: return .Derivation(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 2: return .DerivationPathParse(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 3: return .DescKeyFromXPriv(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 4: return .DescPubKeyFromDescSecretKey(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 5: return .DescSecretKeyFromDescKey(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 6: return .ExtendedKeyFromMnemonic(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 7: return .ExtendedKeyFromXPriv(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 8: return .MnemonicParsing(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 9: return .XPrivFromExtendedKey(
            message: try FfiConverterString.read(from: buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    static func write(_ value: KeyDerivationError, into buf: Writer) {
        switch value {

        

        
        case let .Derivation(message):
            buf.writeInt(Int32(1))
            FfiConverterString.write(message, into: buf)
        case let .DerivationPathParse(message):
            buf.writeInt(Int32(2))
            FfiConverterString.write(message, into: buf)
        case let .DescKeyFromXPriv(message):
            buf.writeInt(Int32(3))
            FfiConverterString.write(message, into: buf)
        case let .DescPubKeyFromDescSecretKey(message):
            buf.writeInt(Int32(4))
            FfiConverterString.write(message, into: buf)
        case let .DescSecretKeyFromDescKey(message):
            buf.writeInt(Int32(5))
            FfiConverterString.write(message, into: buf)
        case let .ExtendedKeyFromMnemonic(message):
            buf.writeInt(Int32(6))
            FfiConverterString.write(message, into: buf)
        case let .ExtendedKeyFromXPriv(message):
            buf.writeInt(Int32(7))
            FfiConverterString.write(message, into: buf)
        case let .MnemonicParsing(message):
            buf.writeInt(Int32(8))
            FfiConverterString.write(message, into: buf)
        case let .XPrivFromExtendedKey(message):
            buf.writeInt(Int32(9))
            FfiConverterString.write(message, into: buf)

        
        }
    }
}


extension KeyDerivationError: Equatable, Hashable {}

extension KeyDerivationError: Error { }


public enum KeyGenerationError {

    
    
    // Simple error enums only carry a message
    case EntropyGeneration(message: String)
    
    // Simple error enums only carry a message
    case MnemonicFromEntropy(message: String)
    
}

fileprivate struct FfiConverterTypeKeyGenerationError: FfiConverterRustBuffer {
    typealias SwiftType = KeyGenerationError

    static func read(from buf: Reader) throws -> KeyGenerationError {
        let variant: Int32 = try buf.readInt()
        switch variant {

        

        
        case 1: return .EntropyGeneration(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 2: return .MnemonicFromEntropy(
            message: try FfiConverterString.read(from: buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    static func write(_ value: KeyGenerationError, into buf: Writer) {
        switch value {

        

        
        case let .EntropyGeneration(message):
            buf.writeInt(Int32(1))
            FfiConverterString.write(message, into: buf)
        case let .MnemonicFromEntropy(message):
            buf.writeInt(Int32(2))
            FfiConverterString.write(message, into: buf)

        
        }
    }
}


extension KeyGenerationError: Equatable, Hashable {}

extension KeyGenerationError: Error { }


public enum SigningError {

    
    
    // Simple error enums only carry a message
    case MessageHashing(message: String)
    
    // Simple error enums only carry a message
    case SecretKeyParse(message: String)
    
}

fileprivate struct FfiConverterTypeSigningError: FfiConverterRustBuffer {
    typealias SwiftType = SigningError

    static func read(from buf: Reader) throws -> SigningError {
        let variant: Int32 = try buf.readInt()
        switch variant {

        

        
        case 1: return .MessageHashing(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 2: return .SecretKeyParse(
            message: try FfiConverterString.read(from: buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    static func write(_ value: SigningError, into buf: Writer) {
        switch value {

        

        
        case let .MessageHashing(message):
            buf.writeInt(Int32(1))
            FfiConverterString.write(message, into: buf)
        case let .SecretKeyParse(message):
            buf.writeInt(Int32(2))
            FfiConverterString.write(message, into: buf)

        
        }
    }
}


extension SigningError: Equatable, Hashable {}

extension SigningError: Error { }


public enum WalletError {

    
    
    // Simple error enums only carry a message
    case BdkWallet(message: String)
    
    // Simple error enums only carry a message
    case ChainBackendClient(message: String)
    
    // Simple error enums only carry a message
    case ChainSync(message: String)
    
    // Simple error enums only carry a message
    case GetBalance(message: String)
    
    // Simple error enums only carry a message
    case OpenDatabase(message: String)
    
    // Simple error enums only carry a message
    case OpenDatabaseTree(message: String)
    
}

fileprivate struct FfiConverterTypeWalletError: FfiConverterRustBuffer {
    typealias SwiftType = WalletError

    static func read(from buf: Reader) throws -> WalletError {
        let variant: Int32 = try buf.readInt()
        switch variant {

        

        
        case 1: return .BdkWallet(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 2: return .ChainBackendClient(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 3: return .ChainSync(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 4: return .GetBalance(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 5: return .OpenDatabase(
            message: try FfiConverterString.read(from: buf)
        )
        
        case 6: return .OpenDatabaseTree(
            message: try FfiConverterString.read(from: buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    static func write(_ value: WalletError, into buf: Writer) {
        switch value {

        

        
        case let .BdkWallet(message):
            buf.writeInt(Int32(1))
            FfiConverterString.write(message, into: buf)
        case let .ChainBackendClient(message):
            buf.writeInt(Int32(2))
            FfiConverterString.write(message, into: buf)
        case let .ChainSync(message):
            buf.writeInt(Int32(3))
            FfiConverterString.write(message, into: buf)
        case let .GetBalance(message):
            buf.writeInt(Int32(4))
            FfiConverterString.write(message, into: buf)
        case let .OpenDatabase(message):
            buf.writeInt(Int32(5))
            FfiConverterString.write(message, into: buf)
        case let .OpenDatabaseTree(message):
            buf.writeInt(Int32(6))
            FfiConverterString.write(message, into: buf)

        
        }
    }
}


extension WalletError: Equatable, Hashable {}

extension WalletError: Error { }

fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    static func write(_ value: [String], into buf: Writer) {
        let len = Int32(value.count)
        buf.writeInt(len)
        for item in value {
            FfiConverterString.write(item, into: buf)
        }
    }

    static func read(from buf: Reader) throws -> [String] {
        let len: Int32 = try buf.readInt()
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: buf))
        }
        return seq
    }
}

public func `initNativeLoggerOnce`(`minLevel`: LogLevel)  {
    try!
    
    rustCall() {
    
    lipabusinesslib_882b_init_native_logger_once(
        FfiConverterTypeLogLevel.lower(`minLevel`), $0)
}
}


public func `generateMnemonic`() throws -> [String] {
    return try FfiConverterSequenceString.lift(
        try
    
    rustCallWithError(FfiConverterTypeKeyGenerationError.self) {
    
    lipabusinesslib_882b_generate_mnemonic($0)
}
    )
}



public func `deriveKeys`(`network`: Network, `mnemonicString`: [String]) throws -> LipaKeys {
    return try FfiConverterTypeLipaKeys.lift(
        try
    
    rustCallWithError(FfiConverterTypeKeyDerivationError.self) {
    
    lipabusinesslib_882b_derive_keys(
        FfiConverterTypeNetwork.lower(`network`), 
        FfiConverterSequenceString.lower(`mnemonicString`), $0)
}
    )
}



public func `signMessage`(`message`: String, `secretKey`: String) throws -> String {
    return try FfiConverterString.lift(
        try
    
    rustCallWithError(FfiConverterTypeSigningError.self) {
    
    lipabusinesslib_882b_sign_message(
        FfiConverterString.lower(`message`), 
        FfiConverterString.lower(`secretKey`), $0)
}
    )
}



public func `generateKeypair`() throws -> KeyPair {
    return try FfiConverterTypeKeyPair.lift(
        try
    
    rustCallWithError(FfiConverterTypeKeyGenerationError.self) {
    
    lipabusinesslib_882b_generate_keypair($0)
}
    )
}



/**
 * Top level initializers and tear down methods.
 *
 * This is generated by uniffi.
 */
public enum LipabusinesslibLifecycle {
    /**
     * Initialize the FFI and Rust library. This should be only called once per application.
     */
    func initialize() {
    }
}